PXC-2948: wsrep_min_log_verbosity - add variable
percona/percona-xtradb-cluster pull request #1016
Opened 2020-03-18 14:09 UTC by borys-belinsky

2020-03-19 05:21 UTC, kennt-percona approved these changes
lgtm

2020-03-19 11:21 UTC, kamil-holubicki requested changes

2020-03-19 11:21 UTC, kamil-holubicki commented on doc/source/wsrep-system-index.rst
> +This variable defines the *minimum* logging verbosity for the given
Not exactly. This variable affects only logs that come from wsrep/galera replication part. Server logs are untouched.
Please see the description in the last comment of https://jira.percona.com/browse/PXC-2948
'wsrep_min_log_verbosity' defines the minimum logging verbosity from wsrep/galera. Its default value is 3

2020-03-19 11:21 UTC, kamil-holubicki commented on doc/source/wsrep-system-index.rst
> +The effective log verbosity cannot be lower than the value of
As above. New variable affects only wsrep/galera part.

It defines minimum desired verbosity from wsrep/galera regardless of what is set to log_error_verbosity'.

Example:
wsrep_min_log_verbosity = 3;
log_error_verbosity = 1;
We see only error/system logs from server parts + all logs from wsrep/galera part

wsrep_min_log_verbosity = 1;
log_error_verbosity = 3;
We see all logs from server part and all logs from wsrep/galera part

Please refer to the table included in the Jira ticket.

2020-03-25 08:16 UTC, kamil-holubicki approved these changes
lgtm

2020-03-25 18:44 UTC, merged