PXC-3128: High priority transactions should work with WSREP
percona/percona-xtradb-cluster pull request #1042
Opened 2020-04-03 10:45 UTC by dutow

Issue: when wsrep is running, high priority transactions weren't able to
kill normal priority transactions. This basically broke the scenario
where a PXC node is also part of a normal replication setup.

Root cause: we intentionally broke this feature in 5.7, in commit
5be95d8ff766. The comment/commit message explains that high priority
transactions aren't how galera works, an dshould be disabled.

Compared to that statement codership fixed HPTs also in 5.7, in commit
f2dd26e10785, by translating the HPT kill logic into wsrep functions.

After merging the codership fix in 5.7, we never reverted our
workaround.

For 8.0, we didn't even port f2dd26e10785, we only ported our disabling
"patch".

Fix:

* Reverting 5be95d8ff766
* Porting f2dd26e10785 to 8.0/galera4
* Removed the assert(0)
* Adding some of the high priority tests to the galera suite to ensure
that they don't break in the future
* This commit also improves the start_transactin_high_prio mtr include
so it works when used together with --debug

Remaining issue: as shown by two TODO comments in the tests, we report a
different error message in some cases compared to basic InnoDB behavior.
This doesn't result in any other behavior change however, we can fix it
later when time permits.

2020-04-06 20:49 UTC, kamil-holubicki requested changes

2020-04-06 20:49 UTC, kamil-holubicki commented on storage/innobase/trx/trx0trx.cc
>      // TODO: G-4
Do we still need this 'todo'?

2020-04-06 20:49 UTC, kamil-holubicki commented on storage/innobase/trx/trx0trx.cc
> +        victim_trx->lock.was_chosen_as_deadlock_victim = TRUE;
true

2020-04-06 20:49 UTC, kamil-holubicki commented on mysql-test/suite/galera/t/high_prio_trx_1.test
> +--connect(con1,localhost,root,,test)
multiple occurences.
All galera tests to be sure that we are connected to the proper node use 
--connection node_1 
and if another connection to the same node is needed they create new connection like
--connect node_1a, 127.0.0.1, root, , test, $NODE_MYPORT_1
--connection node_1a

2020-04-06 20:49 UTC, kamil-holubicki commented on mysql-test/suite/galera/t/high_prio_trx_2.test
> +--connection default
multiple occurences.
Is the idea here check for replication result (use --connection node_2), or what is on the node where we did changes (in such case --connection node_1)

2020-04-06 20:49 UTC, kamil-holubicki commented on mysql-test/suite/galera/t/high_prio_trx_2.test
> +
Multiple occurences:
include wait_unitl_count_sessions.inc

2020-04-07 06:46 UTC, dutow commented on mysql-test/suite/galera/t/high_prio_trx_2.test
> +--connection default
The original tests work on a single node. Here I wanted to test things on another node, to see that the query correctly replicates with galera.

2020-04-07 07:07 UTC, dutow commented
https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/24/

2020-04-07 08:01 UTC, kamil-holubicki approved these changes

2020-04-08 06:28 UTC, merged