PXC-3153: SQL failure in SST donor thread leaves the server hanging
percona/percona-xtradb-cluster pull request #1057
Opened 2020-04-14 07:05 UTC by dutow

Issue: if the donor thread exits with an error before the SST process
was started, it leaves the spawning thread waiting for a signal forever.
This results in the entire server hanging.

Fix: also send this signal if donor bootstrap sql statements fail.

2020-04-14 09:06 UTC, kamil-holubicki requested changes

2020-04-14 09:06 UTC, kamil-holubicki commented on sql/wsrep_sst.cc
> +
When node becomes  a donor its state is shifted:
Shifting DONOR/DESYNCED -> JOINED

If Galera applier thread fails to start sst_donor_thread, it rejoins the cluster. However when sst_donor_thread is started it is detached and it is up to this thread to signal sst finish and trigger rejoining. This is done by calling
Wsrep_server_state::instance().sst_sent(gtid, -err);

I'm afraid that  doing just this will  left the node in desync state.

2020-04-14 09:41 UTC, dutow commented on sql/wsrep_sst.cc
> +
It works, the server notices the failure and shifts the status back to synced, I verified that.

2020-04-15 07:53 UTC, kamil-holubicki commented on sql/wsrep_sst.cc
> +
I did this:

if (true) {
//   if (err) {


Then started cluster (node1) and then joined with node2.
node1 went 

[Galera] server n1 state change: synced -> donor

and stayed in this state.

2020-04-16 12:29 UTC, dutow commented on sql/wsrep_sst.cc
> +
As we discussed on slack, in this case, the error isn't set, which is different compared to the real error case.

2020-04-16 14:13 UTC, kamil-holubicki approved these changes

2020-04-16 14:16 UTC, merged