PXC-3170 - Backport PXC-3154 - Thread pooling hangs on shutdown
percona/percona-xtradb-cluster pull request #1075
Opened 2020-04-22 20:51 UTC by altmannmarcelo

Problem
When wsrep_close_client_connections is called, it closes connections
abruptly. This is ok on shutdown, however, same function is also called
when we set wsrep_cluster_address dynamically and when setting
wsrep_reject_queries=ALL_KILL, which fails to deliver
proper notification to thread_pool threads.

Fix
Adjust wsrep_close_client_connections to first signal the thd as killed
then attempt to close the connection.

2020-04-22 20:51 UTC, altmannmarcelo commented
mtr - https://pxc.cd.percona.com/job/pxc57-test-mtr/53/

2020-04-24 20:31 UTC, peterschwaller commented
I've edited the title to avoid matches with the original Jira issue.

2020-05-13 13:55 UTC, kamil-holubicki requested changes

2020-05-13 13:55 UTC, kamil-holubicki commented on sql/mysqld.cc
> +class Set_wsrep_kill_client_conn : public Do_THD_Impl {
Code formatting does not conform clang 5.0

2020-05-13 13:58 UTC, kamil-holubicki commented
Please remember about doing null merge 5.7 -> 8.0

2020-06-02 19:11 UTC, kamil-holubicki approved these changes

2020-06-04 08:57 UTC, merged