PXC-3138: Upgrade - PXC 5.7 nodes
percona/percona-xtradb-cluster pull request #1080
Opened 2020-04-23 15:57 UTC by borys-belinsky

2020-04-23 16:06 UTC, altmannmarcelo requested changes

2020-04-23 16:06 UTC, altmannmarcelo commented on doc/source/howtos/upgrade_guide.rst
> +   following error message:
The message can vary depending on the query. So I would adjust the working to something like:

In this case, the system reports a message like below:

2020-04-23 16:06 UTC, altmannmarcelo commented on doc/source/howtos/upgrade_guide.rst
> +      query. Default database: 'test'. Query: 'BEGIN', Error_code: 22
```suggestion
      query. Default database: '[DB NAME]'. Query: '[QUERY]', Error_code: 22
```

2020-04-23 17:48 UTC, altmannmarcelo commented on doc/source/howtos/upgrade_guide.rst
> +``super_read_only`` enabled.
remove until PXC-3189 is completed

2020-04-24 11:34 UTC, kathy-williamson approved these changes
I would request that we add another ticket to research how to make this message a meaningful message for the situation

2020-04-24 18:59 UTC, altmannmarcelo approved these changes
LGTM

2020-04-27 10:26 UTC, merged