Pxc 2979 new cluster encrypt cluster traffic 8.0
percona/percona-xtradb-cluster pull request #1086
Opened 2020-04-27 10:30 UTC by borys-belinsky

2020-04-27 12:59 UTC, rameshvs02 commented on doc/source/security/encrypt-traffic.rst
> +certificates on all nodes.
It will be great if we highlight this `It is important that your cluster use the same SSL
certificates on all nodes.`

2020-04-27 13:27 UTC, tplavcic approved these changes
LGTM

2020-04-28 18:21 UTC, hrvojem requested changes
This still doesn't show steps how to setup the encryption on the cluster. When do I need to have the certs in place? How do I roll the encryption to the cluster?

2020-04-28 18:21 UTC, hrvojem commented on doc/source/security/encrypt-traffic.rst
> +enables automatic configuration of SSL encryption thereby encrypting
"automatic" where I need to manually copy over cert files to all the nodes, stop each node, change the config file and start it again before it automatically works?

2020-05-07 19:09 UTC, hrvojem requested changes

2020-05-07 19:09 UTC, hrvojem commented on doc/source/configure.rst
> +
For 8.0 service isn't started after installation, so this step isn't needed anymore (unless user manually started the service after installation)

2020-05-07 19:09 UTC, hrvojem commented on doc/source/security/encrypt-traffic.rst
> +
Note that encryption can't be enabled on a running cluster. If it was disabled before the cluster was bootstrapped, cluster needs to stopped, encryption set up, and bootstrapped again.

2020-05-07 19:09 UTC, hrvojem commented on doc/source/configure.rst
> +
in 8.0 service isn't automatically started after installation, so this step isn't needed (unless user manually started the service).

2020-05-07 19:26 UTC, merged