PS-3326 Enhance Data At Rest Encryption Documentation
percona/percona-xtradb-cluster pull request #1162
Opened 2020-06-17 19:38 UTC by patrickbirch

Modified management/data_at_rest_encryption

In 5.7, only file-per-tablespaces and temporary files

2020-06-18 12:40 UTC, kathy-williamson requested changes
This sentence doesn't make sense.  What is meant by what is after the )? 
Data-in-transit can be encrypted using SSL connections (details are available in the `encrypt traffic documentation <https://www.percona.com/doc/percona-xtradb-cluster/LATEST/security/encrypt-traffic.html>`_) and data-at-rest only.


This sentence needs to be corrected - If the user has a bootstrapped a node with the keyring enabled, then the upcoming nodes of the
cluster either inherit the keyring (encrypted key) from the donor node
has a - the a should be deleted 
inherit should be inherits 

5.6 does not have encrypted tablespace - please make tablespace plural 

change - 'and SST on joiner is' to 'and SST on a joiner is to'

change 'recommends using same keyring_plugin ' to 'recommends using the same keyring_plugin'
change 'an error is notified during' to 'an error is raised during'

this is confusing - If some nodes of the cluster are unable to connect to the vault-server, this
relates only to these specific nodes: e.g. if node-1 can connect, and
node-2 is not, only node-2 refuses to start. If the server has
pre-existing encrypted objects and, on reboot, the server fails to connect to the
vault-server, the objects are not accessible.
Suggested change - 
If any node of the cluster is unable to connect to the vault-server the encrypted objects on that server will not be accessible.

2020-06-18 14:00 UTC, patrickbirch commented
Made requested changes.

2020-06-23 10:17 UTC, mohitj1988 approved these changes
LGTM

2020-07-28 14:17 UTC, kathy-williamson approved these changes

2020-07-29 11:00 UTC, merged