PXC-3634 Erroneous documentation on Bootstrapping XtradbCluster
percona/percona-xtradb-cluster pull request #1411
Opened 2021-04-09 15:19 UTC by patrickbirch

Changes to be committed:
	modified:   source/configure.rst

2021-04-27 12:18 UTC, altmannmarcelo approved these changes
Change looks good to me, I would double-check this with @EvgeniyPatlan since he knows the correct path for the configuration files.

2021-04-30 10:40 UTC, EvgeniyPatlan requested changes

2021-04-30 10:40 UTC, EvgeniyPatlan commented on doc/source/configure.rst
> +add the following configuration variables to :file:`/etc/mysql/percona-xtradb-cluster.conf.d/wsrep.cnf`
on rpm based systems there is no mysql directory in /etc

2021-05-14 06:47 UTC, EvgeniyPatlan approved these changes

2021-06-02 16:27 UTC, merged