PXC-3584 : Assertion failure: lock0lock.cc:6588:!(&trx->mutex)->is_owned()
percona/percona-xtradb-cluster pull request #1463
Opened 2021-07-07 14:17 UTC by satya-bodapati

https://jira.percona.com/browse/PXC-3584

When does replaying of trx happen?

1. Two transactions that are not conflicting at certification level but
   are conflicting at trx commit can lead to situation where one trx
   can be replayed. (See below for example)
2. Trx is replayed only if Victim will have higher seqno than the trx
   that initiated the abort
3. During the replay, before replay is initiated, if a new trx holds
   locks that will be required by replayed trx, replayed trx will try
   to BF Abort the new trx that is open and uncommitted

Problem:
--------
When a trx is about to be replayed and if there exists a conflicting
transaction, the replaying trx will try to BF Abort the conflicting
trx.

During this BF-Abort, an assertion occured because replaying trx
didn't set the BF-abort thread id.

Fix:
----
Replaying transactions should set proper thread id to do BF Aborts.

2021-07-08 09:16 UTC, satya-bodapati commented
https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/273/

2021-07-09 11:12 UTC, venkatesh-prasad-v requested changes
Thank you for working on this issue. Nice work on the test case.
If you don't mind, I have a few suggestions. Please see below.

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on sql/service_wsrep.cc
> +  DBUG_ASSERT(bf_thd->thread_id() != 0);
Upstream has removed support for DBUG_ASSERT in 8.0.25 by https://github.com/percona/percona-server/commit/6889e5c00a51f6d8f9c79def33f6d55226f31f9a

Can you change it to just `assert()` so that there will be one less place to change when we merge 8.0.25?

```suggestion
  assert(bf_thd->thread_id() != 0);
```

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +--disconnect node_2
I think there is no need to disconnect `node_1` and `node_2` connections.

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.cnf
> +!include suite/galera/galera_optimistic_pa.cnf
There is no need for this `.cnf` file. You can remove this.

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +--source include/count_sessions.inc
1. Please use `--source suite/galera/include/galera_have_debug_sync.inc` as this test needs galera library with debug_sync functionality.
2. Please use the more restrictive incs in the beginning.
```suggestion
--source suite/galera/include/galera_have_debug_sync.inc
--source include/galera_cluster.inc
--source include/count_sessions.inc
```

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +--echo # This trx is used for grab conflicting locks just before
```suggestion
--echo # This trx is used for grabbing conflicting locks just before 
```
OR
```suggestion
--echo # This trx is used to grab conflicting locks just before 
```

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +SET AUTOCOMMIT=ON;
Not required for this test.

2021-07-09 11:12 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +SELECT COUNT(*) = 1 FROM t1 WHERE f2 = 'c';
Can we validate that data is consistent on both servers?

Either this
```
--let $diff_servers = 1 2 
--source include/diff_servers.inc
```

Or this
```
--let $galera_diff_statement = SELECT * FROM t1;
--source include/galera_diff.inc
```

2021-07-14 11:20 UTC, satya-bodapati commented on mysql-test/suite/galera/t/pxc_trx_replay_bf_abort.test
> +--disconnect node_2
Ah, these are not established by this test. Good catch

2021-07-14 12:42 UTC, satya-bodapati commented
> Thank you for working on this issue. Nice work on the test case.
> If you don't mind, I have a few suggestions. Please see below.
> 
> Edit: There is a typo in the commit message
> 
> > During this BF-Abort, an assertion occured because replaying trx
> > didn't set the BF-abort thread id.
> 
> `s/occured/occurred`

will address this last (as part of squash)

2021-07-14 12:45 UTC, venkatesh-prasad-v reviewed
Thank you for working on the review comments. The patch looks good now.
Please squash the commits and update the commit message for the final approval.

2021-07-14 13:04 UTC, satya-bodapati commented
> Thank you for working on the review comments. The patch looks good now.
> Please squash the commits and update the commit message for the final approval.

squashed

2021-07-14 13:05 UTC, venkatesh-prasad-v approved these changes
Approved

2021-07-14 13:34 UTC, satya-bodapati commented
> Approved

Thank you!

2021-07-14 13:35 UTC, merged