8.0 pxc 3444
percona/percona-xtradb-cluster pull request #1488
Opened 2021-09-03 15:42 UTC by nitendra-bhosle

2021-09-14 09:15 UTC, kamil-holubicki requested changes
Hi, the change looks fine, but please write a detailed explanation in the commit message (and maybe something inside the code as well) why we need it.
This behavior is specific for PXC only where DML can be replicated in TOI mode. This is used by pt-table-checksum tool which injects 99997 version into the insert.. select query

2021-09-20 08:15 UTC, kamil-holubicki commented
Please merge just approved https://github.com/percona/wsrep-lib/pull/8, update wsrep repo poiner, squash commits, update commit message as requested.

2021-09-21 06:36 UTC, dutow requested changes
As we discussed on slack, please do not merge this as is into the 8.0 branch, because the wsrep-lib submodule also contains changes for the 8.0.25 merge.

Either target the PR to the release-8.0.25 branch, or wait until we merge back the release branch.

2021-09-21 06:41 UTC, nitendra-bhosle commented
> As we discussed on slack, please do not merge this as is into the 8.0 branch, because the wsrep-lib submodule also contains changes for the 8.0.25 merge.
> 
> Either target the PR to the release-8.0.25 branch, or wait until we merge back the release branch.

Yeah , sure . I will revert these changes   and wait for release branch . This bug will be fixed only if we get changes from wsrep-lib library .

2021-09-21 07:42 UTC, kamil-holubicki commented
I don't know which wsrep-lib hash goes into 8.0.25, but if the change related to PXC-3444 is included, I would merge this PR to 8.0.25 release branch as well (here we have only tests, fix is in wsrep-lib).
On the flip side, if 8.0.25 wsrep-lib does not contain fix for PXC-3444, as Zsolt said, we need to wait with merging this PR till 8.0.25 release branch is merged back to 8.0.

Other than that, all looks good, please squash before merging.

2021-12-16 18:36 UTC, kamil-holubicki approved these changes
LGTM

2021-12-20 05:43 UTC, nitendra-bhosle commented
Jenkins : https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/370/

2021-12-20 09:53 UTC, nitendra-bhosle commented
New Jenkins : https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/371/

2022-03-03 14:17 UTC, dutow approved these changes

2022-03-03 14:20 UTC, merged