[PXC-3824] fix: Require= systemd unit typo changed to Requires=
percona/percona-xtradb-cluster pull request #1533
Opened 2021-11-22 15:05 UTC by AgileStas

2021-11-22 16:54 UTC, vorsel approved these changes

2021-11-22 19:52 UTC, EvgeniyPatlan requested changes

2021-11-22 19:52 UTC, EvgeniyPatlan commented on build-ps/percona-xtradb-cluster.spec
> +            %if 0%{?rhel} == 7
< 8

2021-11-23 07:14 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1533) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1533) it.</sub>

2021-11-23 11:28 UTC, EvgeniyPatlan approved these changes

2021-11-30 11:36 UTC, merged