Release 8.0.25
percona/percona-xtradb-cluster pull request #1535
Opened 2021-11-23 14:03 UTC by vorsel

2021-11-26 10:23 UTC, kamil-holubicki requested changes
Changes look good for me however, PR has merge conflicts. 
Please resolve. In case of troubles with c++ conflicts do not hesitate to ping me for help :)

2021-11-29 08:11 UTC, EvgeniyPatlan approved these changes

2021-11-29 09:39 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1535) before we can accept your contribution.<br/>**7** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: vorsel<br/>:white_check_mark: nitendra-bhosle<br/>:white_check_mark: kamil-holubicki<br/>:white_check_mark: EvgeniyPatlan<br/>:white_check_mark: venkatesh-prasad-v<br/>:white_check_mark: dutow<br/>:white_check_mark: satya-bodapati<br/>:x: Luis Donoso<br/>:x: ldonoso<br/>:x: oleksandr-kachan<br/><hr/>**Luis Donoso** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1535) it.</sub>

2021-11-29 09:57 UTC, kamil-holubicki approved these changes
LGTM

2021-11-29 10:32 UTC, merged