PXC-3704: wsrep_max_ws_size not linked to repl.max_ws_size when defined in configuration file
percona/percona-xtradb-cluster pull request #1562
Opened 2021-12-27 10:04 UTC by venkatesh-prasad-v

https://jira.percona.com/browse/PXC-3704

Problem
=======
Server variable `wsrep_max_ws_size` and provider option `repl.max_size` have
been linked together from a long time. However, passing `wsrep_max_ws_size` in
the cnf file has no effect on the provider's repl.max_size option and the
server shows different values post startup.

Solution
========
1. When only `wsrep_max_ws_size` is passed during startup, then the same value
   used as the maximum writeset size.
2. When only `repl.max_ws_size` is passed during startup, then the same value
   used as the maximum writeset size.
3. When both `repl.max_ws_size` and `wsrep_max_ws_size` are passed during
   startup, then `repl.max_ws_size` takes precedence over `wsrep_max_ws_size`.

2022-01-19 11:36 UTC, satya-bodapati reviewed
@venkatesh-prasad-v why have two variables for the same configuration max_write_set_size? Is this a mistake by upstream?

2022-01-19 11:44 UTC, venkatesh-prasad-v commented
@satya-bodapati Yes. This exists on upstream as well.

https://galeracluster.com/library/documentation/galera-parameters.html#repl-max-ws-size
https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-max-ws-size

2022-01-19 11:49 UTC, satya-bodapati commented
> @satya-bodapati Yes. This exists on upstream as well.
> 
> https://galeracluster.com/library/documentation/galera-parameters.html#repl-max-ws-size https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-max-ws-size

Hmm, ideally the right fix would be to deprecate the wsrep variable wsrep_max_ws_size? :) what do you think?

2022-01-19 13:54 UTC, satya-bodapati requested changes
LGTM, minor comments

2022-01-19 13:54 UTC, satya-bodapati commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
may be create a sync_cluster.inc?

2022-01-19 13:54 UTC, satya-bodapati commented on sql/wsrep_mysqld.cc
> +/*
use doxygen style /** and @return ..

2022-01-19 14:01 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
I had already created https://jira.percona.com/browse/PXC-3210 for the same. Looks like it is the time now :)

2022-01-19 14:19 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
Looks like we already have `wsrep_wait_membership.inc` for waiting on the number of nodes. I'll reuse them.

2022-01-19 14:24 UTC, satya-bodapati commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
Rename it to wsrep_sync_cluster.inc

2022-01-19 14:26 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
IMO, wsrep_sync_cluster sounds a bit ambiguous as it doesn't sync the cluset, but only waits until the cluster has the desied number of members. So, I think the current name is enough.

2022-01-19 14:31 UTC, satya-bodapati commented on mysql-test/suite/galera/t/galera_repl_max_ws_size.test
> +--source include/wait_condition.inc
ok fine with me

2022-01-24 07:02 UTC, satya-bodapati approved these changes
LGTM! Please squash and merge

2022-01-24 13:34 UTC, merged