5.7.36 codership mysql wsrep 5.7.35 25.27
percona/percona-xtradb-cluster pull request #1578
Opened 2022-01-18 07:24 UTC by nitendra-bhosle

2022-01-18 07:26 UTC, nitendra-bhosle commented
Jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/262/

2022-01-18 09:14 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1578) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1578) before we can accept your contribution.<br/>**1** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: nitendra-bhosle<br/>:x: mkaruza<br/>:x: abychko<br/>:x: temeo<br/>:x: pacheco<br/>:x: ayurchen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1578) it.</sub>

2022-01-19 05:48 UTC, nitendra-bhosle commented
Latest Jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/264/

2022-01-19 07:36 UTC, venkatesh-prasad-v requested changes

2022-01-19 07:36 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_rsync.sh
> +||||||| merged common ancestors
Version Control Marker will cause rsync tests to fail. Please remove this.


>2022-01-19T07:14:07.489217Z 0 [Note] WSREP: Initiating SST/IST transfer on JOINER side (wsrep_sst_rsync --role 'joiner' --address '127.0.0.1:13009' --datadir '/home/venki/work/pxc/review/nitendra/bld/mysql-test/var/mysqld.2/data/' --defaults-file '/home/venki/work/pxc/review/nitendra/bld/mysql-test/var/my.cnf' --defaults-group-suffix '.2' --parent '39359' --mysqld-version '5.7.36-39'   '' ) 
/home/venki/work/pxc/review/nitendra/bld/scripts/wsrep_sst_rsync: line 181: syntax error near unexpected token `||'
>2022-01-19T07:14:07.661565Z 0 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_rsync --role 'joiner' --address '127.0.0.1:13009' --datadir '/home/venki/work/pxc/review/nitendra/bld/mysql-test/var/mysqld.2/data/' --defaults-file '/home/venki/work/pxc/review/nitendra/bld/mysql-test/var/my.cnf' --defaults-group-suffix '.2' --parent '39359' --mysqld-version '5.7.36-39'   '' 
	Read: '(null)'

2022-01-19 07:36 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_rsync.sh
> +#connect = ${WSREP_SST_OPT_ADDR%/*}
We reverted Codership's stunnel encryption in rsync by commit 998da9b5d. So this block can completely be removed.

2022-01-19 07:36 UTC, venkatesh-prasad-v commented on sql/log_event.cc
> +     */
IIUC, [Bug#80821](https://bugs.mysql.com/bug.php?id=80821) is already fixed in PS and PXC. So I'm not sure if this is really necessary.

@dutow Can you please share your opinions on this?

2022-01-26 17:11 UTC, nitendra-bhosle commented
New Jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/267/

2022-01-28 20:34 UTC, nitendra-bhosle commented
Jenkins: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/268/

2022-02-01 10:07 UTC, venkatesh-prasad-v commented on sql/log_event.cc
> +#if defined(WITH_WSREP)
Please change it to `#ifdef WITH_WSREP` in order to make it work with our `check_src` tool.

2022-02-01 10:07 UTC, venkatesh-prasad-v commented on sql/sql_parse.cc
> -  LOCK_wsrep_thd too. */
Please revert this change (bring back the comment).

2022-02-01 10:59 UTC, venkatesh-prasad-v approved these changes
lgtm

2022-02-01 13:41 UTC, venkatesh-prasad-v approved these changes

2022-02-01 14:23 UTC, merged