Release 8.0.27
percona/percona-xtradb-cluster pull request #1593
Opened 2022-03-07 13:17 UTC by kamil-holubicki

2022-03-07 13:18 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1593) before we can accept your contribution.<br/>**2** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: kamil-holubicki<br/>:white_check_mark: EvgeniyPatlan<br/>:x: Luis Donoso<br/>:x: rahulmalik87<br/>:x: percona-ysorokin<br/><hr/>**Luis Donoso** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1593) it.</sub>

2022-03-08 10:35 UTC, venkatesh-prasad-v requested changes
Few comments

1. Please update the `XB_8x_REQUIRED_VERSION` in `scripts/wsrep_sst_xtrabackup-v2.sh` to 8.0.27.
2. Please update the xtrabackup tag used in `cmake/dev_helper.cmake` file.

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on unittest/gunit/group_replication/group_replication_gcs_mysql_network_provider-t.cc
> +                            std::string(), gtid,
Please run clang-format-10 on all files touched by this commit (e867c567c7da6edf95e019bc729ad6421c023b94)

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on sql/wsrep_mysqld.cc
>       0, PSI_DOCUMENT_ME},
Can we have the new names given to galera threads start with `galera_`?

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on storage/innobase/handler/ha_innodb.cc
> +          (ulint)field->pack_length(), false, 0, 0, &prebuilt->compress_heap);
Why this change?

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on storage/innobase/handler/ha_innodb.cc
> +        ptr = row_mysql_read_blob_ref(&len, ptr, len, false, 0, 0, &prebuilt->compress_heap);
Why this change?

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on sql/mysqld.cc
> +  { &key_THREAD_wsrep_applier, "THREAD_wsrep_applier", "applier", PSI_FLAG_SINGLETON, 0, PSI_DOCUMENT_ME},
Can we name it as `wsrep_applier` instead if just `applier`?

2022-03-08 10:35 UTC, venkatesh-prasad-v commented on mysql-test/mysql-test-run.pl
> -  tokudb
Is it a better idea to remove the test files as well?

2022-03-08 12:56 UTC, kamil-holubicki commented on sql/wsrep_mysqld.cc
>       0, PSI_DOCUMENT_ME},
Unfortunately we can't. There is limitation in register_thread_class()
``` assert(strlen(info->m_os_name) < PFS_MAX_OS_NAME_LENGTH - 3); ```
and
```#define PFS_MAX_OS_NAME_LENGTH 16```
so we've got only 12 characters

2022-03-08 12:56 UTC, kamil-holubicki commented on unittest/gunit/group_replication/group_replication_gcs_mysql_network_provider-t.cc
> +                            std::string(), gtid,
done

2022-03-08 13:00 UTC, kamil-holubicki commented on storage/innobase/handler/ha_innodb.cc
> +        ptr = row_mysql_read_blob_ref(&len, ptr, len, false, 0, 0, &prebuilt->compress_heap);
```row_mysql_read_blob_ref()``` declaration has changed

2022-03-08 13:00 UTC, kamil-holubicki commented on storage/innobase/handler/ha_innodb.cc
> +          (ulint)field->pack_length(), false, 0, 0, &prebuilt->compress_heap);
```row_mysql_read_blob_ref()``` declaration has changed

2022-03-08 13:01 UTC, venkatesh-prasad-v commented on sql/wsrep_mysqld.cc
>       0, PSI_DOCUMENT_ME},
Ok. Then let us go with the current names only.

2022-03-08 13:06 UTC, kamil-holubicki commented on sql/mysqld.cc
> +  { &key_THREAD_wsrep_applier, "THREAD_wsrep_applier", "applier", PSI_FLAG_SINGLETON, 0, PSI_DOCUMENT_ME},
likewise. Limitation.

2022-03-08 13:33 UTC, kamil-holubicki commented on mysql-test/mysql-test-run.pl
> -  tokudb
Removed all TokuDB related MTR suites.

2022-03-09 10:17 UTC, venkatesh-prasad-v approved these changes
Please revert the changes in `.gitmodules` before merging.

2022-03-14 10:08 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/434/

2022-03-16 14:46 UTC, merged