5.7.37 psmerge part 1
percona/percona-xtradb-cluster pull request #1605
Opened 2022-04-05 14:26 UTC by nitendra-bhosle

2022-04-05 14:26 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1605) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1605) before we can accept your contribution.<br/>**8** out of **20** committers have signed the CLA.<br/><br/>:white_check_mark: patrickbirch<br/>:white_check_mark: venkatesh-prasad-v<br/>:white_check_mark: alina-derkach-oaza<br/>:white_check_mark: kamil-holubicki<br/>:white_check_mark: nitendra-bhosle<br/>:white_check_mark: satya-bodapati<br/>:white_check_mark: AgileStas<br/>:white_check_mark: EvgeniyPatlan<br/>:x: Bharathy Satish<br/>:x: bkandasa<br/>:x: phulakun<br/>:x: zmur<br/>:x: pedrolgomes<br/>:x: salmankhan123417<br/>:x: wikigurram<br/>:x: gkodinov<br/>:x: oleksandr-kachan<br/>:x: karthik-kamath<br/>:x: rahulmalik87<br/>:x: avbelov23<br/><hr/>**Bharathy Satish** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1605) it.</sub>

2022-04-05 14:32 UTC, nitendra-bhosle commented
Jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/283/

2022-04-13 11:26 UTC, nitendra-bhosle commented
Updated jenkins : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/286/

2022-04-18 03:46 UTC, venkatesh-prasad-v requested changes

2022-04-18 03:46 UTC, venkatesh-prasad-v commented on sql/rpl_mi.cc
> +      from->get_info(user, sizeof(user), (char *) "test") ||
This change re-introduces the bug that was fixed in commit efd3968b98fd6affe5b582da34f4a7fc95c546e0.
Can you please revert this change and check if something can be fixed in test itself?

2022-04-19 08:09 UTC, venkatesh-prasad-v approved these changes
LGTM

2022-04-19 10:07 UTC, venkatesh-prasad-v approved these changes

2022-04-19 14:27 UTC, kamil-holubicki approved these changes
lgtm

2022-04-19 14:43 UTC, merged