5.7.37 codership mysql wsrep 5.7.36 25.28
percona/percona-xtradb-cluster pull request #1621
Opened 2022-04-26 13:03 UTC by nitendra-bhosle

2022-04-26 13:20 UTC, venkatesh-prasad-v requested changes

2022-04-26 13:20 UTC, venkatesh-prasad-v commented on WSREP_VERSION
> +WSREP_VERSION_PATCH=28
In `cmake/wsrep.cmake`, we have set `WSREP_PATCH_VERSION=57`, but it is 28 here. This causes inconsistencies in the versioning. Could you please fix it?

2022-04-26 13:20 UTC, venkatesh-prasad-v commented on cmake/wsrep.cmake
> ->>>>>>> wsrep_5.7.36-25.28
I think it is better we retain upstream's logic of fetching the `WSREP_PATCH_VERSION` from the WSREP_VERSION file. Could you please revert these changes?

2022-04-26 13:35 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1621) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1621) before we can accept your contribution.<br/>**2** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: EvgeniyPatlan<br/>:white_check_mark: nitendra-bhosle<br/>:x: bkandasa<br/>:x: abychko<br/>:x: sciascid<br/>:x: ldonoso<br/>:x: Luis Donoso<br/>:x: sjaakola<br/>:x: temeo<br/><hr/>**Luis Donoso** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1621) it.</sub>

2022-04-28 05:56 UTC, venkatesh-prasad-v approved these changes
lgtm

2022-04-28 13:44 UTC, nitendra-bhosle commented
Jenkins run : https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/293/

2022-04-28 13:52 UTC, merged