PXC-3449: Galera fails after MDL BF-BF conflict
percona/percona-xtradb-cluster pull request #1669
Opened 2022-08-08 15:27 UTC by kamil-holubicki

(post merge fix)

https://jira.percona.com/browse/PXC-3449

Problem:
It has been discovered that executing DROP INDEX in parallel to DML can
cause BF-BF abort and node shutdown.

Cause:
The problem is similar to already merged fixes to BF-BF in scope of the
same ticket. When we have 2 tables, parent and child, DROP INDEX
executed in parallel to DML can cause abort of already certified and
replicated DML. In such a case DML is replayed locally, but can cause
BF-BF abort on replica. This is because the certification process has
not enough information about tables dependencies, which leads to faulty
certification process/transactions ordering.

Solution:
Add parent/child tables to certification keys set when executing
DROP/CREATE INDEX. This causes local DML to fail certification.

2022-08-08 15:32 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/520/

2022-08-15 13:35 UTC, venkatesh-prasad-v commented on sql/wsrep_server_service.cc
> +         Introducing a delay is enough for testing. */
Looks a leftover from PXC-3982 bugfix. Please remove these changes.

2022-08-15 13:47 UTC, venkatesh-prasad-v requested changes

2022-08-15 13:47 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera_nbo/t/galera_bf_bf.test
> +#set global wsrep_log_conflicts=1;
Unused?

2022-08-25 09:40 UTC, kamil-holubicki commented on sql/wsrep_server_service.cc
> +         Introducing a delay is enough for testing. */
removed

2022-08-25 09:40 UTC, kamil-holubicki commented on mysql-test/suite/galera_nbo/t/galera_bf_bf.test
> +#set global wsrep_log_conflicts=1;
removed

2022-08-25 11:06 UTC, venkatesh-prasad-v approved these changes

2022-08-30 10:21 UTC, merged