PXC 5.7.40 merge part1
percona/percona-xtradb-cluster pull request #1709
Opened 2022-12-05 13:16 UTC by VarunNagaraju

2022-12-05 13:16 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1709) before we can accept your contribution.<br/>**5** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: alina-derkach-oaza<br/>:white_check_mark: adivinho<br/>:white_check_mark: voodam<br/>:white_check_mark: patrickbirch<br/>:white_check_mark: kamil-holubicki<br/>:x: sreedhars<br/>:x: i-rinat<br/>:x: mysql-builder@oracle.com<br/>:x: bkandasa<br/>:x: GBuella<br/>:x: salmankhan123417<br/>:x: karthik-kamath<br/>:x: percona-ysorokin<br/>:x: VarunNagaraju<br/>:x: oleksandr-kachan<br/><hr/>**mysql-builder@oracle.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1709) it.</sub>

2022-12-05 13:22 UTC, VarunNagaraju commented
Jenkins test results of the part 1 merge: https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-param/359/#showFailuresLink
Two test failures: main.merge and main.merge_mmap.

2022-12-06 22:02 UTC, kamil-holubicki requested changes

2022-12-06 22:02 UTC, kamil-holubicki commented on MYSQL_VERSION
> +PXC_VERSION_EXTRA=62
This should be bumped to next even number, so 63

2022-12-06 22:02 UTC, kamil-holubicki commented on packaging/WiX/mysql_server.wxs.in
>        <?if "@Platform@"="x64"?>
Interesting, that we had a conflict in this file... :)

2022-12-06 22:02 UTC, kamil-holubicki commented on sql/log.h
>  /* 26 for regular timestamp, plus 7 (".123456") when using micro-seconds */
My suggestion is to move the new block before #ifdef WITH_WSREP.
This way we will have WSREP-related things at the end of the file, not in the middle

2022-12-06 22:02 UTC, kamil-holubicki commented on build-ps/percona-server.spec
> +%global compatver             5.6.51
content of build-ps directory should not be changed

2022-12-07 11:46 UTC, VarunNagaraju commented on build-ps/percona-server.spec
> +%global compatver             5.6.51
Done.

2022-12-07 11:46 UTC, VarunNagaraju commented on sql/log.h
>  /* 26 for regular timestamp, plus 7 (".123456") when using micro-seconds */
Done.

2022-12-07 12:10 UTC, kamil-holubicki approved these changes
lgtm

2022-12-15 07:37 UTC, VarunNagaraju commented
Jenkins run with PXB 2.4.27: https://pxc.cd.percona.com/job/pxc-5.7-param/363/
Test failures: 
rpl.rpl_mts_gtids_restart_slave_io_lost_trx_with_master_delay : Seems like a flaky test. Verified.

2022-12-15 07:50 UTC, merged