PXC-4211: Server aborts on binary log rotation
percona/percona-xtradb-cluster pull request #1796
Opened 2023-05-09 10:13 UTC by kamil-holubicki

https://jira.percona.com/browse/PXC-4211

Problem:
When the binlog is rotated because of reaching its maximum size the server aborts with assertion.

Cause:
Upstream commit 9b4809f2fc3bcdfb90c77a463912e133d36acc53 introduced the optimization which skips blocking operation of compressing GTID sets during storing them into GTIDs table during binlog rotation. Now GTIDs are stored as well, but compression is delegated to compress_gtid_table thread.
Before the upstream fix, compression and store were triggered by connection context, but actual work was done in context of clone_gtid_thread which is not wsrep_thread so wsrep commit hooks were not executed.
After the upstream fix GTIDs are stored in table from connection context. When this implicit transaction commits, commit hooks are executed causing assertion.

Solution:
Skip wsrep commit hooks execution for implicit internal transaction of storing GTIDS.

2023-05-09 10:14 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1657/

2023-05-10 08:01 UTC, venkatesh-prasad-v requested changes

2023-05-10 08:01 UTC, venkatesh-prasad-v commented on sql/rpl_gtid_persist.cc
> +  thd->run_wsrep_commit_hooks = false;
`table_access_ctx.deinit()` is called from multiple places in this file. We should probably skip running wsrep commit hooks in all places. Can we introduce a RAII class in `sql/thd_raii.h` to do the cleanup and use it inside `Gtid_table_access_context::deinit()` so that we cover all cases.

2023-05-10 08:01 UTC, venkatesh-prasad-v commented on mysql-test/suite/wsrep/t/binlog_rotation.test
> +INSERT INTO t1(b) SELECT (b) FROM t1;
Can we just to the following to force binlog rotation?
```
CREATE TABLE t1(c1 varchar(8192));
SET GLOBAL binlog_cache_size = 4096;
--connect(con1,localhost,root,,)
BEGIN;
INSERT INTO t1 VALUES (repeat('a', 8192));
COMMIT;

2023-05-10 13:31 UTC, kamil-holubicki commented on sql/rpl_gtid_persist.cc
> +  thd->run_wsrep_commit_hooks = false;
I have reworked the fix. Now it relies on `is_operating_gtid_table_implicitly` variable.

2023-05-10 13:34 UTC, kamil-holubicki commented on mysql-test/suite/wsrep/t/binlog_rotation.test
> +INSERT INTO t1(b) SELECT (b) FROM t1;
`binlog_cache_size` does not cause binlog rotation. I've replaced a series of `insert into ... select` with your proposal.

2023-05-10 13:36 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/job/pxc-8.0-pipeline-parallel-mtr/1663/

2023-05-11 09:52 UTC, venkatesh-prasad-v approved these changes

2023-05-11 09:55 UTC, merged