PXC-4034: Using sql_log_bin=0 breaks GTID consistency
percona/percona-xtradb-cluster pull request #1860
Opened 2023-12-12 11:09 UTC by kamil-holubicki

https://jira.percona.com/browse/PXC-4034

Problem:
If binlogging is enabled globally, but it is disabled in the session scope, transactions executed within this session advance 'gtid_executed' As transactions are not binlogged, after the node restart, 'gtid_purged' is populated with gtids related to these transactions. When the node acts as the source for async replica, it causes replica to fail, because source is not able to serve not logged, but gtid-related transactions.

Cause:
PXC, even if binlog is disabled, uses binlog infrastructure to cache binlog events for the purpose of creation of Galera writesets. If binlog is disabled, logging to the file is skipped.
GTID is generated during group commit binlog flush stage. PXC flow goes through this stage if binlog is enabled generating GTIDs for every transaction, even if later the transaction is not binlogged.

Solution:
If binlogging is disabled for the particular thread, force the execution path as if gtid_mode was equal OFF.

2023-12-12 11:09 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/view/PXC%205.7/job/pxc-5.7-pipeline/5910/

2023-12-13 11:59 UTC, venkatesh-prasad-v requested changes

2023-12-13 11:59 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_as_master_gtid.test
> +--let $assert_text = 'gitd_executed changed'
```suggestion
--let $assert_text = 'gtid_executed has not changed'
```

2023-12-13 11:59 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_as_master_gtid.test
> +--let $assert_text = 'gtid_purged is not empty'
```suggestion
--let $assert_text = 'gtid_purged is empty'
```

2023-12-13 11:59 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera/t/galera_as_master_gtid.test
> +--let $assert_text = 'INSERT was replicated, but it shouldn't'
```suggestion
--let $assert_text = 'INSERT was not replicated'
```

2023-12-13 17:02 UTC, venkatesh-prasad-v approved these changes
LGTM

2023-12-14 07:56 UTC, merged