PS 8.1.0 merge
percona/percona-xtradb-cluster pull request #1865
Opened 2023-12-28 14:40 UTC by kamil-holubicki

2023-12-28 14:40 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1865) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=1865) before we can accept your contribution.<br/>**5** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: EvgeniyPatlan<br/>:white_check_mark: adivinho<br/>:white_check_mark: inikep<br/>:white_check_mark: kamil-holubicki<br/>:white_check_mark: venkatesh-prasad-v<br/>:x: percona-ysorokin<br/>:x: oleksandr-kachan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=1865) it.</sub>

2023-12-28 14:42 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/view/8.0%20parallel%20MTR/job/pxc-8.0-pipeline-parallel-mtr-innovative/13/

2024-01-01 09:11 UTC, venkatesh-prasad-v requested changes

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on .cirrus.yml
> +>>>>>>> ps/Percona-Server-8.1.0-1
This file still has conflict markes. Please resolve conflicts in this file and remove all conflict markers.

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on azure-pipelines.yml
> +>>>>>>> ps/Percona-Server-8.1.0-1
This file still has conflict markes. Please resolve conflicts in this file and remove all conflict markers.

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/debian/control
> -Package: libperconaserverclient22
Why this change? Does it mean that `libperconaserverclient22` is not supported anymore?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/debian/control
>           stunnel
I think we can remove `stunnel` as it is not used anywhere.

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/debian/percona-xtradb-cluster-server.postinst
> -echo -e "\tmysql -e \"INSTALL COMPONENT 'file://component_percona_udf'\""
I think we can retain this in PXC.

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/rpm/mysql-5.7-sharedlib-rename.patch
>  +  LINK_LIBRARIES mysqlclient client_base ${MY_READLINE_LIBRARY}
Shouldn't we use `EDITLINE_LIBRARY` instead of `MY_READLINE_LIBRARY`?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on etq
> +[1m+++ b/percona-xtradb-cluster-galera[m
I think this file may be removed.

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on mysql-test/suite/galera_sr/t/GCF-1043A-master.opt.tmp
> +--wsrep-debug=4
Does MTR handle `.tmp` extension file as well?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/CMakeLists.txt.8.0.34
> +# Copyright (c) 2006, 2023, Oracle and/or its affiliates.
Is this file required?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/CMakeLists.txt.conflict
> +# Copyright (c) 2006, 2023, Oracle and/or its affiliates.
Is this file required?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/systemd/mysqld.service.in.pxc
> +# Copyright (c) 2015, 2023, Oracle and/or its affiliates.
Is this a new file or a renamed file?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on sql/kh_backtrace.cc
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_backtrace.cc
Remove this file

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on sql/kh_backtrace.h
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_backtrace.h
Remove this file

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on sql/kh_debug.cc
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_debug.cc
Remove this file

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on sql/kh_debug.h
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_debug.h
Remove this file

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +# 3. Its own backup
```suggestion
# 3. Backup from the current version of PXC
```

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +# If the cluster is on 8.1 the only way to upgrade it to 8.4 is to go throug
```suggestion
# If the cluster is on 8.1 the only way to upgrade it to 8.4 is to go through
```

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +XB_PREV_LTS_REQUIRED_VERSION="8.0.35"
One thought. 

If PXB-8.0.34 can take backup of PXC-8.0.35, then why can't we ship the lower version (PXC-8.0.34) in our packages to support upgrades from previous GA/LTS?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +            wsrep_log_error "${local_version_str} (the same version as this node)."
```suggestion
            wsrep_log_error "${local_version_full_str} (the same version as this node)."
```

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/debian/percona-xtradb-cluster-server.install
> +# KH: usr/lib/mysql/plugin/data_masking.ini
Is this required?

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/percona-xtradb-cluster.spec
> +# KH: %attr(644, root, root) %{_libdir}/mysql/plugin/data_masking.ini
Likewise

2024-01-01 09:11 UTC, venkatesh-prasad-v commented on build-ps/pxc_builder.sh
> +set -x
Is this still required?

2024-01-02 15:48 UTC, kamil-holubicki commented on .cirrus.yml
> +>>>>>>> ps/Percona-Server-8.1.0-1
done

2024-01-02 15:48 UTC, kamil-holubicki commented on azure-pipelines.yml
> +>>>>>>> ps/Percona-Server-8.1.0-1
done

2024-01-02 15:51 UTC, kamil-holubicki commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +XB_PREV_LTS_REQUIRED_VERSION="8.0.35"
I'm not sure I get your point. From backward compatibility point of view it doesn't matter if it is PXB 8.0.34 or 80.35. 
PXB 8.0.35 will be able to handle all SSTs from 8.0.x donors

2024-01-02 15:55 UTC, kamil-holubicki commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +            wsrep_log_error "${local_version_str} (the same version as this node)."
No, it is fine. If the node is 8.4.17 the allowed donors are:
1. 8.0.x
2. 8.3.1
3. 8.4.n
Version mean maj.min

2024-01-02 15:56 UTC, kamil-holubicki commented on build-ps/debian/percona-xtradb-cluster-server.install
> +# KH: usr/lib/mysql/plugin/data_masking.ini
fixed

2024-01-02 15:57 UTC, kamil-holubicki commented on build-ps/percona-xtradb-cluster.spec
> +# KH: %attr(644, root, root) %{_libdir}/mysql/plugin/data_masking.ini
fixed

2024-01-02 15:57 UTC, kamil-holubicki commented on build-ps/pxc_builder.sh
> +set -x
fixed

2024-01-02 16:00 UTC, kamil-holubicki commented on etq
> +[1m+++ b/percona-xtradb-cluster-galera[m
done

2024-01-02 16:01 UTC, kamil-holubicki commented on scripts/CMakeLists.txt.conflict
> +# Copyright (c) 2006, 2023, Oracle and/or its affiliates.
fixed

2024-01-02 16:01 UTC, kamil-holubicki commented on scripts/systemd/mysqld.service.in.pxc
> +# Copyright (c) 2015, 2023, Oracle and/or its affiliates.
fixed

2024-01-02 16:03 UTC, kamil-holubicki commented on sql/kh_backtrace.h
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_backtrace.h
fixed

2024-01-02 16:03 UTC, kamil-holubicki commented on sql/kh_backtrace.cc
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_backtrace.cc
fixed

2024-01-02 16:03 UTC, kamil-holubicki commented on scripts/CMakeLists.txt.8.0.34
> +# Copyright (c) 2006, 2023, Oracle and/or its affiliates.
fixed

2024-01-02 16:04 UTC, kamil-holubicki commented on sql/kh_debug.cc
> +/home/kamil/repo/kh-dev/tools/kh-debug/kh_debug.cc
fixed

2024-01-02 16:04 UTC, kamil-holubicki commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +# 3. Its own backup
fixed

2024-01-02 16:05 UTC, kamil-holubicki commented on scripts/wsrep_sst_xtrabackup-v2.sh
> +# If the cluster is on 8.1 the only way to upgrade it to 8.4 is to go throug
fixed

2024-01-02 16:08 UTC, kamil-holubicki commented on mysql-test/suite/galera_sr/t/GCF-1043A-master.opt.tmp
> +--wsrep-debug=4
file removed

2024-01-02 16:22 UTC, kamil-holubicki commented on build-ps/rpm/mysql-5.7-sharedlib-rename.patch
>  +  LINK_LIBRARIES mysqlclient client_base ${MY_READLINE_LIBRARY}
This change is inherited from PS

2024-01-02 16:28 UTC, kamil-holubicki commented on build-ps/debian/percona-xtradb-cluster-server.postinst
> -echo -e "\tmysql -e \"INSTALL COMPONENT 'file://component_percona_udf'\""
added

2024-01-02 16:29 UTC, kamil-holubicki commented on build-ps/debian/control
>           stunnel
removed

2024-01-02 16:32 UTC, kamil-holubicki commented on build-ps/debian/control
> -Package: libperconaserverclient22
As per standard merge process, I left build files unchanged.
I've only adjusted them to be able to locally create deb and rpm packages, but most probably we need more help from Packaging Team to do it right.

2024-01-03 11:11 UTC, kamil-holubicki commented
https://pxc.cd.percona.com/view/8.0%20parallel%20MTR/job/pxc-8.0-pipeline-parallel-mtr-innovative/19/

2024-01-03 14:07 UTC, venkatesh-prasad-v requested changes

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on mysql-test/mysql-test-run.pl
> +  percona_innodb
Are these new suites which we are planning to introduce?

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on build-ps/rpm/mysql-5.7-sharedlib-rename.patch
>  +  LINK_LIBRARIES mysqlclient client_base ${MY_READLINE_LIBRARY}
PS-8.1 now uses `EDITLINE_LIBRARY` and the change was introduced by this [commit](https://github.com/percona/percona-server/commit/e58eafc56cfa1756ffeb06ab0f01bdf850da8d58#diff-d3a19e3ebe94729d2ee8cb455688b7da65feb009918161af24188a9ae6c0f8aa) 

See https://github.com/percona/percona-server/blob/Percona-Server-8.1.0-1/build-ps/rpm/mysql-5.7-sharedlib-rename.patch#L15-L16

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on build-ps/build-binary.sh
>      LIBLIST="libnuma.so libgssapi.so libldap_r-2.4.so.2 liblber-2.4.so.2 libaio.so libprocps.so libcrypto.so libssl.so libgcrypt.so libreadline.so libtinfo.so libsasl2.so libbrotlidec.so libbrotlicom
`libreadline.so` has been removed in PS. Let's remove it in PXC as well.

![image](https://github.com/percona/percona-xtradb-cluster/assets/63641998/afc35aa0-2270-44d6-ab2f-1ffc897fcaa6)

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on azure-pipelines.yml
> ->>>>>>> percona/ps/release-8.1.0-1
`libreadline-dev` has been removed here as well.

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on build-ps/debian/control
> +               libreadline-dev,
I think this may not be needed as are no longer using `libreadline`.

2024-01-03 14:07 UTC, venkatesh-prasad-v commented on build-ps/debian/control
> -Package: libperconaserverclient22-dev
I think this should be left as-is because `libperconaserverclient22` was added in 8.1 as part of commit https://github.com/percona/percona-server/commit/7b65f76093d1de30be8499cb74de06d97a339d3c and I think we should retain dependencies on `libperconaserverclient22`

2024-01-03 15:56 UTC, kamil-holubicki commented on mysql-test/mysql-test-run.pl
> +  percona_innodb
PS 8.1 moved percona tess to separate suites.

2024-01-03 16:06 UTC, kamil-holubicki commented on build-ps/build-binary.sh
>      LIBLIST="libnuma.so libgssapi.so libldap_r-2.4.so.2 liblber-2.4.so.2 libaio.so libprocps.so libcrypto.so libssl.so libgcrypt.so libreadline.so libtinfo.so libsasl2.so libbrotlidec.so libbrotlicom
done

2024-01-03 16:07 UTC, kamil-holubicki commented on build-ps/debian/control
> +               libreadline-dev,
done

2024-01-03 16:11 UTC, kamil-holubicki commented on build-ps/debian/control
> -Package: libperconaserverclient22-dev
I changed it as suggested, but as said before I think we need help from @EvgeniyPatlan for proper packages creation.
For now I just adjusted these scripts to be able to generate deb/rpm packages locally (and didn't test if they work)

2024-01-03 16:49 UTC, venkatesh-prasad-v commented on mysql-test/mysql-test-run.pl
> +  percona_innodb
Ok. Got it. Thanks for the explanation.

2024-01-03 16:52 UTC, venkatesh-prasad-v approved these changes
LGTM

2024-01-04 13:40 UTC, merged