Release notes and updated install instructions
percona/percona-xtradb-cluster pull request #289
Opened 2016-09-22 08:27 UTC by azhebel

2016-09-22 10:13 UTC, kbauskar commented
LGTM

2016-09-23 16:33 UTC, kbauskar commented
Besides this I am okay with all the changes

Changes to doc/source/install/apt.rst this I don't think I understand.

2016-09-27 07:47 UTC, hrvojem requested changes

2016-09-27 07:47 UTC, hrvojem commented on doc/source/install/upgrade_guide.rst
For debian/ubuntu you'll need to manually stop the service after upgrade because service is automatically started during the install/upgrade process.

2016-09-27 07:47 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.14-26.17.rst
> +
Bad version/link, should be: 5.7.14-8 https://www.percona.com/doc/percona-server/5.7/release-notes/Percona-Server-5.7.14-8.html

2016-09-27 07:47 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.14-26.17.rst
> +
Not sure if mentioning these are cleared out. Ping David.

2016-09-28 19:33 UTC, azhebel commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.14-26.17.rst
> +
David asked to add them: https://jira.percona.com/browse/RM-160?focusedCommentId=132520&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-132520

2016-09-28 20:32 UTC, closed without merging