Doc updates for 5.7.16
percona/percona-xtradb-cluster pull request #365
Opened 2016-12-08 10:06 UTC by azhebel

This contains only updates specific to 5.7 for now. After 5.6 updates are reviewed, I will add them to this PR, along with release notes.

2016-12-08 10:54 UTC, kbauskar requested changes

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/encrypt-traffic.rst
> +By default, it is disabled, meaning that you need to configure SSL manually
Please this stmt

By default, variable is false. Turning it to true will auto-configure use of SSL encryption for SST, IST and internode traffic.

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/encrypt-traffic.rst
> +When you enable automatic configuration of SSL encryption,
This section is confusing.
@kennt-percona can you suggest better rewording.

Message has to clearly come

* If user set pxc-..=ON then user don't need to configure anything for SST/IST traffic
* if user set pxc-=ON and also specific SST/IST configuration what happens ?

@azhebel this needs to organized such that it comes up clearly for end-user.

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +Maintenance Mode
s/Maintenance mode/ProxySQL assisted Maintenance Mode/g

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +  and waits for a predefined period (60 seconds by default),
s/60/10/gc

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +  (60 seconds by default), until existing transactions finish.
s/60/10/gc

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +  until existing transactions finish.
get rid of following

"until existing transactions finish"

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +  (60 seconds by default), until existing transactions finish.
get rid of
"until existing transaction finish"

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +  When ProxySQL detects that the mode is set to ``SHUTDOWN``,
s/SHUTDONW/MAINTENANCE/g

?????

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +
This doesn't apply to MAINTENANCE mode.
Existing large transaction will continue. ProxySQL will not start new transaction.
(In shutdown case server was going down)

2016-12-08 10:54 UTC, kbauskar commented on doc/source/howtos/proxysql.rst
> +   and avoids openning new connections for transactions,
and ProxySQL avoids opening new connection/or starting new transaction.

2016-12-08 10:54 UTC, kbauskar commented on doc/source/wsrep-system-index.rst
> +   :version 5.7.15: Variable introduced
5.7.16

2016-12-08 10:54 UTC, kbauskar commented on doc/source/wsrep-system-index.rst
> +By default, it waits for 60 seconds until running transactions finish
60 -> 10

2016-12-08 10:54 UTC, kbauskar commented on doc/source/wsrep-system-index.rst
> +You can indcrease the value to accomodate for long-running transactions.
increase

2016-12-08 10:54 UTC, kbauskar commented on doc/source/wsrep-system-index.rst
> +   :version 5.7.15: Variable introduced
5.7.16

2016-12-12 06:49 UTC, kennt-percona commented on doc/source/howtos/encrypt-traffic.rst
> +This will override encryption settings, but not other options related to SST,
Maybe it would be better to remove this line (starting with "This will override...").

2016-12-12 07:34 UTC, kennt-percona commented on doc/source/howtos/encrypt-traffic.rst
> +When you enable automatic configuration of SSL encryption,
Preliminaries
The usage of SSL within PXC requires that the SSL certificates/key files all be the same (or generated from the same CA).  So, before turning on SSL auto-configuration, it is necessary to create the appropriate SSL certs/keys and copy them to the nodes before startup. The location of the CA, certificate, and key files are specified with the 'ssl-ca', 'ssl-cert', and 'ssl-key' options respectively (in the [mysqld] section). If these options are not specified, then the files are assumed to be in the data directory as 'ca.pem', 'server-cert.pem', and 'server-key.pem' respectively.
(link to the section where we talked about how to generate the SSL file)

If the files are kept in their default location in the datadir, then the only option that needs to be set is 'pxc-encrypt-cluster-traffic=ON'.

PXC SSL auto-configuration occurs in two steps:
(1) The SSL files are located.
PXC first looks for the 'ssl-ca', 'ssl-cert' and 'ssl-key' options in the my.cnf file.  If these are not found, then the default names in the datadir ('ca.pem', 'server-cert.pem', and 'server-key.pem') files are used.  Note that the '[sst]' section is not searched.

(2) The Galera and SST configuration settings are overridden.
To ensure proper functioning, the Galera/SST options are then overridden to use these values for the SSL files. Other SSL settings are unchanged. The effect of the SSL auto-configuration is equivalent to setting the my.cnf as such:

[mysqld]
wsrep_provider_options=”socket.ssl_key=server-key.pem;socket.ssl_cert=server-cert.pem;socket.ssl_ca=ca.pem”

[sst]
encrypt=4
ssl-key=server-key.pem
ssl-ca=ca.pem
ssl-cert=server-cert.pem

2016-12-13 09:43 UTC, azhebel commented on doc/source/howtos/encrypt-traffic.rst
> +When you enable automatic configuration of SSL encryption,
All of this is mentioned in a more compact and structured way.

2016-12-13 11:01 UTC, kbauskar approved these changes
Let Kenn go over it once.
Otherwise ok from my side.

2016-12-13 13:07 UTC, kennt-percona commented on doc/source/howtos/encrypt-traffic.rst
> +The following settings are applied or overridden::
Maybe this should be written as:
The following settings will be applied and will override any existing settings.

2016-12-14 15:55 UTC, merged