release notes for pxc 5.7.20-29.24
percona/percona-xtradb-cluster pull request #597
Opened 2018-01-25 09:22 UTC by fiowro

2018-01-25 11:30 UTC, hrvojem requested changes

2018-01-25 11:30 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +* `Percona Server 5.7.20 <http://www.percona.com/doc/percona-server/5.7/release-notes/Percona-Server-5.7.20-17.html>`_
It's based on https://www.percona.com/doc/percona-server/5.7/release-notes/Percona-Server-5.7.20-18.html there was no 5.7.20-17.

2018-01-25 21:25 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +
it should be full Percona Server version, `5.7.20-18`.

2018-01-26 00:53 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  timeout.
rephrasing

-----
a usability improvement was made to timeout error messages, the name of the configuration variable which caused the timeout was added to the message.

2018-01-26 00:54 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  last committed and last applied transaction numbers.
added commas

----
A new variable :variable:`wsrep_last_applied`, in addition
to :variable:`wsrep_last_committed`, one was introduced to clearly separate
last committed and last applied transaction numbers.

2018-01-26 01:43 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  id to be assigned to the running thread.
this one is difficult to explain

----

fixed an abort caused by an early read of the query_id, ensuring that valid ids are assigned to subsequent transactions.

2018-01-26 01:44 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  configuration setting making it not to be taken into account.
"wsrep debug" should be "wsrep_debug"

2018-01-26 01:59 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  than the first one. Bug fixed :bug:`1741818`
Fixed a bug where a ``LOAD DATA`` command used with GTIDS was executed on one node, but the other nodes would receive less rows than the first one.

2018-01-26 02:29 UTC, kennt-percona commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.20-29.24.rst
> +  fix infinite loop at mysqladmin ping fail because of nonexistent ping user.
and to fix an infinite loop that occurred due to mysqladmin ping failing because of a nonexistent ping user.

2018-01-26 17:38 UTC, hrvojem approved these changes
LGTM

2018-01-30 17:45 UTC, merged