Release notes for PXC 5.6.39-26.25
percona/percona-xtradb-cluster pull request #615
Opened 2018-02-23 16:46 UTC by fiowro

2018-02-23 19:40 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.39-26.25.rst
> +
3.25 ?

2018-02-26 16:13 UTC, kbauskar requested changes

2018-02-26 16:13 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.39-26.25.rst
> +* Galera Replication library 3.25
s/Galera Replication library 3.25/Galera Replication library 3.23/

2018-02-26 16:13 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.39-26.25.rst
> +Fixed Bugs
bugs/issues/

2018-02-26 17:05 UTC, merged