PXC-2061 : PXC 5.7: wsrep_sync_wait not working
percona/percona-xtradb-cluster pull request #625
Opened 2018-03-07 10:33 UTC by kennt-percona

Issue:
When "wsrep_sync_wait=1", which enforces read causality, we can read
the wrong values, depending on timing. This happens because we are
waiting on the commit monitor to be flushed.

Solution:
We need to wait upon the apply monitor instead of the commit monitor.

2018-03-07 10:33 UTC, kennt-percona commented
https://jenkins.percona.com/job/pxc57.test.mtr/466/

2018-03-08 02:59 UTC, kbauskar requested changes

2018-03-08 02:59 UTC, kbauskar commented on mysql-test/suite/galera/t/MW-86-wait1.test
> +--error 1205
Please replace 1205 with error name ER_TIMEOUT (or whatever has been assigned by MySQL)

2018-03-08 03:23 UTC, kbauskar approved these changes

2018-03-08 03:24 UTC, merged