PXC 5.6.40-26.25 Release notes
percona/percona-xtradb-cluster pull request #653
Opened 2018-06-18 23:37 UTC by fiowro

2018-06-19 07:19 UTC, hrvojem requested changes

2018-06-19 07:19 UTC, hrvojem commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.40-26.25.rst
> +  configure RSU wait for active commit connection timeout (in micro-seconds).
Please add complete description to wsrep-system-index.rst. This will also fix DOC-747 (which is blocker for this issue).

2018-06-19 10:17 UTC, kbauskar requested changes

2018-06-19 10:17 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.40-26.25.rst
> +* Galera/Codership WSREP API Release 5.6.40
There is no galera 5.6.40 (last we refresh from was galera-5.6.39)

2018-06-20 02:55 UTC, kbauskar requested changes

2018-06-20 02:55 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.40-26.25.rst
> +* :jirabug:`PXC-2061`: In bounds of |PXC| 5.7 performance improvement, which
Please get rid of this issue....Issue was wrongly linked with 5.6 ticket when it was 5.7 only ticket.

2018-06-20 06:54 UTC, kbauskar approved these changes

2018-06-20 06:57 UTC, hrvojem approved these changes
LGTM

2018-06-20 12:47 UTC, merged