PXC 5.7.24 release notes
percona/percona-xtradb-cluster pull request #733
Opened 2018-12-19 16:53 UTC by fiowro

2018-12-19 17:30 UTC, kbauskar requested changes

2018-12-19 17:30 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.24-31.33.rst
> +* Galera Replication library 3.24
This would be now 3.25

2018-12-19 17:30 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.7.24-31.33.rst
> +* Galera/Codership WSREP API Release 5.7.23
And this would be now 5.7.24

2019-01-02 10:05 UTC, kbauskar approved these changes

2019-01-04 09:11 UTC, hrvojem approved these changes
LGTM

2019-01-04 12:54 UTC, merged