5.6.42-28.30 release notes
percona/percona-xtradb-cluster pull request #734
Opened 2018-12-19 17:26 UTC by fiowro

2018-12-19 17:31 UTC, kbauskar requested changes

2018-12-19 17:31 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.42-28.30.rst
> +* Codership WSREP API release 5.6.41
would be 5.6.42 now.

2018-12-19 17:31 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.42-28.30.rst
> +* Codership Galera library 3.24
would be 3.25 now.

2018-12-19 17:31 UTC, kbauskar commented on doc/source/release-notes/Percona-XtraDB-Cluster-5.6.42-28.30.rst
> +Percona XtraDB Cluster 5.6.42-28.30 on December 20, 2018.
please set date as 4th Jan 2019

2018-12-19 21:18 UTC, hrvojem requested changes
bump the version in conf.py

2019-01-02 10:05 UTC, kbauskar approved these changes

2019-01-04 09:08 UTC, hrvojem approved these changes
LGTM

2019-01-04 12:46 UTC, merged