PXC-2446: Release notes for v5.7.25-31.35
percona/percona-xtradb-cluster pull request #766
Opened 2019-02-27 09:43 UTC by borys-belinsky

2019-02-27 10:45 UTC, kbauskar approved these changes

2019-02-27 10:46 UTC, hrvojem requested changes
version update in conf.py

2019-02-27 10:46 UTC, hrvojem commented on doc/source/install/apt.rst
>  * Ubuntu 17.10 (Artful Aardvark)
Artful support has been dropped

2019-02-28 13:25 UTC, hrvojem approved these changes
LGTM

2019-02-28 13:27 UTC, merged