Updated SST QA script for PXC-8.0 test
percona/percona-xtradb-cluster pull request #780
Opened 2019-03-05 09:30 UTC by rameshvs02

2019-03-14 02:58 UTC, kbauskar reviewed
logic to check version has been replaced in wsrep_sst_common to use better operator. Do consider if you want to change or update to it.

2019-03-14 03:00 UTC, kbauskar requested changes

2019-03-14 03:00 UTC, kbauskar commented on percona-xtradb-cluster-tests/sst/run.sh
> +    if ! check_for_version $MYSQL_VERSION_CHECK "8.0.0" ; then
Can you add comment as to when to use find and when to use which.

2019-03-19 07:42 UTC, rameshvs02 commented on percona-xtradb-cluster-tests/sst/run.sh
> +    if ! check_for_version $MYSQL_VERSION_CHECK "8.0.0" ; then
Done

2019-03-19 08:20 UTC, kbauskar approved these changes

2019-03-19 08:42 UTC, merged