PXB-2688: Fix the name of WSREP_SYNC_WAIT_UPTO_GTID
percona/percona-xtradb-cluster pull request #936
Opened 2020-02-03 12:19 UTC by dutow

2020-02-03 12:19 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=936) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=936) it.</sub>

2020-02-04 03:12 UTC, kbauskar requested changes
I don't see any descriptive commit message. Can we add one explaining the change?

2020-02-04 09:52 UTC, dutow commented
Added. Also removed unrelated formatting changes.

2020-02-05 08:55 UTC, kbauskar approved these changes

2020-02-10 01:20 UTC, kennt-percona approved these changes

2020-02-10 01:20 UTC, merged