PXC-2900: Assertion on implicit transaction commit
percona/percona-xtradb-cluster pull request #940
Opened 2020-02-05 17:01 UTC by kamil-holubicki

https://jira.percona.com/browse/PXC-2900

Suppresed assert in case of wsrep_commit_empty() being called on implicit transaction commit, but commited transaction had only one statement transaction that was rolled back.
The problem was that statement transaction, could append several row keys to writeset and then rollback (i.e. multirow INSERT trying to insert duplicate unique key values). When implicit commit was requested, wsrep_commit_empty() was called which expected empty writeset (assert), however already added keys should be considered as not valid.

2020-02-05 17:01 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=940) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-xtradb-cluster?pullRequest=940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-xtradb-cluster?pullRequest=940) it.</sub>

2020-02-06 04:30 UTC, kbauskar requested changes

2020-02-06 04:30 UTC, kbauskar commented on sql/wsrep_trans_observer.h
> +  thd->wsrep_stmt_transaction_rolled_back = false;
before_statement is not called before each statement executes. Trace the flow of before the statement. We expect the flag to get cleared before the next transaction starts.

2020-02-06 09:19 UTC, kbauskar approved these changes

2020-02-06 19:43 UTC, merged