PXC-3021 chnage package versioning to maj.min.patch-p1.p2
percona/percona-xtradb-cluster pull request #984
Opened 2020-03-05 12:12 UTC by vorsel

2020-03-05 12:22 UTC, EvgeniyPatlan requested changes
please improve rpm build

2020-03-06 00:10 UTC, kennt-percona commented
Shouldn't this  be merged into 8.0 trunk?  why is this being merged into the release-8.0.18 branch?

2020-03-06 09:08 UTC, EvgeniyPatlan commented
> Shouldn't this be merged into 8.0 trunk? why is this being merged into the release-8.0.18 branch?

@kennt-percona it will be merged together wih all other packaging changes from release branch to 9.0 branch. and after that new release branch will be created

2020-03-06 10:49 UTC, EvgeniyPatlan approved these changes

2020-03-06 10:49 UTC, merged