PXC-3045: Release notes - v8.0.18-4.1
percona/percona-xtradb-cluster pull request #994
Opened 2020-03-09 18:44 UTC by borys-belinsky

2020-03-09 19:26 UTC, dbadapt requested changes

2020-03-09 19:26 UTC, dbadapt commented on doc/source/release-notes/Percona-XtraDB-Cluster-8.0.18-4.1.rst
> +- :jirabug:`PXC-3044`: IST is failing with PXC-8.0 upgrade
This will be fixed in 8.0.18-4.1

2020-03-09 19:26 UTC, dbadapt commented on doc/source/release-notes/Percona-XtraDB-Cluster-8.0.18-4.1.rst
> +
There is another one that won't be fixed in the RC
https://jira.percona.com/browse/PXC-3047

2020-03-09 19:26 UTC, dbadapt commented on doc/source/release-notes/Percona-XtraDB-Cluster-8.0.18-4.1.rst
> +Improvements and New Features
This section should be removed for an RC release

2020-03-09 19:26 UTC, dbadapt commented on doc/source/release-notes/Percona-XtraDB-Cluster-8.0.18-4.1.rst
> +- :jirabug:`PXC-3026`: WITH_WSREP code duplication causes mismerges
This is a compile-time issue, remove

2020-03-09 20:16 UTC, dbadapt approved these changes

2020-03-10 01:33 UTC, dbadapt requested changes
We should also tell them how to report issues:

https://jira.percona.com/projects/PXC

2020-03-10 01:33 UTC, dbpercona commented on doc/source/release-notes/Percona-XtraDB-Cluster-8.0.18-4.1.rst
> +
We should give them instructions on how to install:
1. Install percona-release (https://www.percona.com/doc/percona-repo-config/percona-release.html)
2. $ sudo percona-release enable-only pxc-80 experimental

2020-03-19 07:24 UTC, kennt-percona commented on doc/source/conf.py
> +release = '8.0.18-4.1'
Release version should be 8.0.18-9.1

2020-04-22 13:16 UTC, kathy-williamson requested changes
Please  change candadate to candidate

Known Issues section needs to be contain the tickets identified in https://docs.google.com/spreadsheets/d/11ZjIW2hRCATT_AxESQWDf_QekMc2DdZL71_nw5CYyPk/edit#gid=0

2020-04-22 13:20 UTC, EvgeniyPatlan commented on doc/source/conf.py
> +release = '8.0.18-4.1'
we have packages with version 8.0.18-9.3

2020-04-24 20:38 UTC, peterschwaller commented
The Jira issue for this is Done.  Should we Close this PR?

2020-05-11 06:41 UTC, closed without merging